from PyQt5 import QtCore, QtGui, QtWidgets
from Class.functions import *


class MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super(MainWindow, self).__init__()
        self.setObjectName("MainWindow")
        self.resize(800, 600)
        self.setMinimumSize(QtCore.QSize(800, 600))
        self.setMaximumSize(QtCore.QSize(800, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../a/3.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setWindowIcon(icon)
        self.setStyleSheet("background-color: rgb(97, 97, 112);")
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.Bienvenida = QtWidgets.QLabel(self.centralwidget)
        self.Bienvenida.setGeometry(QtCore.QRect(50, 20, 301,  81))
        self.Bienvenida.setAlignment(QtCore.Qt.AlignCenter)
        self.Bienvenida.setObjectName("Bienvenida")
        self.Gastado = QtWidgets.QLabel(self.centralwidget)
        self.Gastado.setGeometry(QtCore.QRect(80, 460, 191, 31))
        self.Gastado.setObjectName("Gastado")
        self.Ingresado = QtWidgets.QLabel(self.centralwidget)
        self.Ingresado.setGeometry(QtCore.QRect(300, 460, 191, 31))
        self.Ingresado.setObjectName("Ingresado")
        self.Utilidades = QtWidgets.QLabel(self.centralwidget)
        self.Utilidades.setGeometry(QtCore.QRect(520, 460, 191, 31))
        self.Utilidades.setObjectName("Utilidades")
        self.NuUtilidades = QtWidgets.QLabel(self.centralwidget)
        self.NuUtilidades.setGeometry(QtCore.QRect(520, 510, 191, 31))
        self.NuUtilidades.setObjectName("NuUtilidades")
        self.NuIngresado = QtWidgets.QLabel(self.centralwidget)
        self.NuIngresado.setGeometry(QtCore.QRect(300, 510, 191, 31))
        self.NuIngresado.setObjectName("NuIngresado")
        self.NuGastado = QtWidgets.QLabel(self.centralwidget)
        self.NuGastado.setGeometry(QtCore.QRect(80, 510, 191, 31))
        self.NuGastado.setObjectName("NuGastado")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(80, 450, 641, 111))
        self.label_8.setStyleSheet("background-color:transparent; border: 2px solid black; border-radius: 10px")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(280, 450, 231, 111))
        self.label_9.setStyleSheet("background-color:transparent; border: 2px solid black")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 29))
        self.menubar.setStyleSheet("QMenuBar{background:rgb(117, 117, 135); font: italic 12pt \"Sitka\"} \n"
"QMenuBar::item:selected{background: rgb(102, 102, 118)}\n"
"")
        self.menubar.setObjectName("menubar")
        self.menuOperaciones = QtWidgets.QMenu(self.menubar)
        self.menuOperaciones.setStyleSheet("QMenu{background-color: rgb(117, 117, 135);}\n"
"QMenu::item:selected{background-color: rgb(102, 102, 118); color: black}")
        self.menuOperaciones.setObjectName("menuOperaciones")
        self.menuTablas = QtWidgets.QMenu(self.menubar)
        self.menuTablas.setStyleSheet("QMenu{background-color: rgb(117, 117, 135);}\n"
"QMenu::item:selected{background-color: rgb(102, 102, 118); color: black}")
        self.menuTablas.setObjectName("menuTablas")
        self.menuPor_dia = QtWidgets.QMenu(self.menuTablas)
        self.menuPor_dia.setObjectName("menuPor_dia")
        self.menuTodas_las_operaciones = QtWidgets.QMenu(self.menuTablas)
        self.menuTodas_las_operaciones.setObjectName("menuTodas_las_operaciones")
        self.menuGraficas = QtWidgets.QMenu(self.menubar)
        self.menuGraficas.setStyleSheet("QMenu{background-color: rgb(117, 117, 135);}\n"
"QMenu::item:selected{background-color: rgb(102, 102, 118); color: black}")
        self.menuGraficas.setObjectName("menuGraficas")
        self.menuTodas_las_operaciones_2 = QtWidgets.QMenu(self.menuGraficas)
        self.menuTodas_las_operaciones_2.setObjectName("menuTodas_las_operaciones_2")
        self.menuPor_dia_2 = QtWidgets.QMenu(self.menuGraficas)
        self.menuPor_dia_2.setObjectName("menuPor_dia_2")
        self.menuExportar = QtWidgets.QMenu(self.menubar)
        self.menuExportar.setStyleSheet("QMenu{background-color: rgb(117, 117, 135);}\n"
"QMenu::item:selected{background-color: rgb(102, 102, 118); color: black}")
        self.menuExportar.setObjectName("menuExportar")
        self.menuInformacion = QtWidgets.QMenu(self.menubar)
        self.menuInformacion.setStyleSheet("QMenu{background-color: rgb(117, 117, 135);}\n"
"QMenu::item:selected{background-color: rgb(102, 102, 118); color: black}")
        self.menuInformacion.setObjectName("menuInformacion")
        self.setMenuBar(self.menubar)
        self.actionGasto = QtWidgets.QAction(self)
        self.actionGasto.triggered.connect(VentanaOperacion)
        self.actionGasto.setObjectName("actionGasto")
        self.actionGastos = QtWidgets.QAction(self)
        self.actionGastos.triggered.connect(lambda: TablesWindows("gastos", "Diario"))
        self.actionGastos.setObjectName("actionGastos")
        self.actionIngresos = QtWidgets.QAction(self)
        self.actionIngresos.triggered.connect(lambda: TablesWindows("ingresos", "Diario"))
        self.actionIngresos.setObjectName("actionIngresos")
        self.actionAmbos = QtWidgets.QAction(self)
        self.actionAmbos.triggered.connect(lambda: TablesWindows("ambos", "Diario"))
        self.actionAmbos.setObjectName("actionAmbos")
        self.actionGastos_2 = QtWidgets.QAction(self)
        self.actionGastos_2.triggered.connect(lambda: TablesWindows("gastos", "Todas"))
        self.actionGastos_2.setObjectName("actionGastos_2")
        self.actionIngresos_2 = QtWidgets.QAction(self)
        self.actionIngresos_2.triggered.connect(lambda: TablesWindows("ingresos", "Todas"))
        self.actionIngresos_2.setObjectName("actionIngresos_2")
        self.actionAmbos_2 = QtWidgets.QAction(self)
        self.actionAmbos_2.triggered.connect(lambda: TablesWindows("ambos", "Todas"))
        self.actionAmbos_2.setObjectName("actionAmbos_2")
        self.actionGastos_3 = QtWidgets.QAction(self)
        self.actionGastos_3.setObjectName("actionGastos_3")
        self.actionIngresos_3 = QtWidgets.QAction(self)
        self.actionIngresos_3.setObjectName("actionIngresos_3")
        self.actionAmbos_3 = QtWidgets.QAction(self)
        self.actionAmbos_3.setObjectName("actionAmbos_3")
        self.actionGastos_4 = QtWidgets.QAction(self)
        self.actionGastos_4.setObjectName("actionGastos_4")
        self.actionIngresos_4 = QtWidgets.QAction(self)
        self.actionIngresos_4.setObjectName("actionIngresos_4")
        self.actionAmbos_4 = QtWidgets.QAction(self)
        self.actionAmbos_4.setObjectName("actionAmbos_4")
        self.actionPDF = QtWidgets.QAction(self)
        self.actionPDF.setObjectName("actionPDF")
        self.actionGuardar_mes = QtWidgets.QAction(self)
        self.actionGuardar_mes.setObjectName("actionGuardar_mes")
        self.actionInformacion = QtWidgets.QAction(self)
        self.actionInformacion.triggered.connect(info)
        self.actionInformacion.setObjectName("actionInformacion")
        self.menuOperaciones.addAction(self.actionGasto)
        self.menuOperaciones.addSeparator()
        self.menuPor_dia.addAction(self.actionGastos)
        self.menuPor_dia.addAction(self.actionIngresos)
        self.menuPor_dia.addAction(self.actionAmbos)
        self.menuTodas_las_operaciones.addAction(self.actionGastos_2)
        self.menuTodas_las_operaciones.addAction(self.actionIngresos_2)
        self.menuTodas_las_operaciones.addAction(self.actionAmbos_2)
        self.menuTablas.addAction(self.menuTodas_las_operaciones.menuAction())
        self.menuTablas.addAction(self.menuPor_dia.menuAction())
        self.menuTodas_las_operaciones_2.addAction(self.actionGastos_3)
        self.menuTodas_las_operaciones_2.addAction(self.actionIngresos_3)
        self.menuTodas_las_operaciones_2.addAction(self.actionAmbos_3)
        self.menuPor_dia_2.addAction(self.actionGastos_4)
        self.menuPor_dia_2.addAction(self.actionIngresos_4)
        self.menuPor_dia_2.addAction(self.actionAmbos_4)
        self.menuGraficas.addAction(self.menuTodas_las_operaciones_2.menuAction())
        self.menuGraficas.addAction(self.menuPor_dia_2.menuAction())
        self.menuExportar.addAction(self.actionPDF)
        self.menuInformacion.addAction(self.actionInformacion)
        self.menubar.addAction(self.menuOperaciones.menuAction())
        self.menubar.addAction(self.menuTablas.menuAction())
        self.menubar.addAction(self.menuGraficas.menuAction())
        self.menubar.addAction(self.menuExportar.menuAction())
        self.menubar.addAction(self.menuInformacion.menuAction())


        self.timer = QtCore.QTimer(self)
        self.timer.setInterval(4000)
        self.timer.timeout.connect(lambda: (ActualizarLabel(self.NuGastado, self.NuIngresado, self.NuUtilidades)))
        self.timer.start()


        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Bienvenida.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600; color:#828296;\">Bienvenido(a)</span></p></body></html>"))
        self.Gastado.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#828296;\">Total Gastado</span></p></body></html>"))
        self.Ingresado.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#828296;\">Total Ingresado</span></p></body></html>"))
        self.Utilidades.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#828296;\">Utilidades</span></p></body></html>"))
        self.NuUtilidades.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#828296;\">Cargando...</span></p></body></html>"))
        self.NuIngresado.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#828296;\">Cargando...</span></p></body></html>"))
        self.NuGastado.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#828296;\">Cargando...</span></p></body></html>"))
        self.menuOperaciones.setTitle(_translate("MainWindow", "Operaciones"))
        self.menuTablas.setTitle(_translate("MainWindow", "Tablas"))
        self.menuPor_dia.setTitle(_translate("MainWindow", "Por dia"))
        self.menuTodas_las_operaciones.setTitle(_translate("MainWindow", "Todas las operaciones"))
        self.menuGraficas.setTitle(_translate("MainWindow", "Graficas"))
        self.menuTodas_las_operaciones_2.setTitle(_translate("MainWindow", "Todas las operaciones"))
        self.menuPor_dia_2.setTitle(_translate("MainWindow", "Por dia"))
        self.menuExportar.setTitle(_translate("MainWindow", "Exportar"))
        self.menuInformacion.setTitle(_translate("MainWindow", "Informacion"))
        self.actionGasto.setText(_translate("MainWindow", "Agregar operación"))
        self.actionGastos.setText(_translate("MainWindow", "Gastos"))
        self.actionIngresos.setText(_translate("MainWindow", "Ingresos"))
        self.actionAmbos.setText(_translate("MainWindow", "Ambos"))
        self.actionGastos_2.setText(_translate("MainWindow", "Gastos"))
        self.actionIngresos_2.setText(_translate("MainWindow", "Ingresos"))
        self.actionAmbos_2.setText(_translate("MainWindow", "Ambos"))
        self.actionGastos_3.setText(_translate("MainWindow", "Gastos"))
        self.actionIngresos_3.setText(_translate("MainWindow", "Ingresos"))
        self.actionAmbos_3.setText(_translate("MainWindow", "Ambos"))
        self.actionGastos_4.setText(_translate("MainWindow", "Gastos"))
        self.actionIngresos_4.setText(_translate("MainWindow", "Ingresos"))
        self.actionAmbos_4.setText(_translate("MainWindow", "Ambos"))
        self.actionPDF.setText(_translate("MainWindow", "PDF"))
        self.actionGuardar_mes.setText(_translate("MainWindow", "Ultimo mes"))
        self.actionInformacion.setText(_translate("MainWindow", "Informacion"))

